### ISSUE TITLE
Error when running shadowissues.py!

### ISSUE THREAD

**Issue by neomatrix369** [trentm/googlecode2github#6]
Below is what I did, and in return got error messages in your script, did I do something wrong?

python shadowissues.py mutability-detector mutability-detector
# Gathering code.google.com/p/mutability-detector issues.
# Gathering any github.com/mutability-detector issues.

Traceback (most recent call last):
  File "shadowissues.py", line 347, in <module>
    sys.exit(main(sys.argv))
  File "shadowissues.py", line 344, in main
    shadow_issues(argv[1], argv[2])
  File "shadowissues.py", line 60, in shadow_issues
    gh_issues = _get_gh_issues(gh_proj)
  File "shadowissues.py", line 258, in _get_gh_issues
    raise RuntimeError("error GET'ing %s: %s" % (url, response["status"]))
RuntimeError: error GET'ing https://api.github.com/repos/mutability-detector/issues?state=open: 404

**Comment by ooxi** [comment]
Hi,

which version of python are you running? Did you execute any commands prior to `python shadowissues.py mutability-detector mutability-detector` or supplied any additional argument?

-- ooxi

**Comment by neomatrix369** [comment]
I didn't , but a friend of mine was able to run another python script. The
problem might have been with the ubuntu installation of mine or how I
installed python on my machine.
